#!/bin/sh
#deploy="false"
deploy="true"

image=PayUtilityBills
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t Service/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push Service/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag Service/${image}:1.0-SNAPSHOT Service/${image}:latest
        docker push Service/${image}:latest
    fi
fi