#!/bin/sh
mvn clean package && docker build -t Service/PayUtilityBills .
docker rm -f PayUtilityBills 2>/dev/null || true && docker run -it --name PayUtilityBills -p 8080:8080 -p 4848:4848 -p 8181:8181 --name PayUtilityBills Service/PayUtilityBills
